name: pika (legacy Python)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: build/test on windows-latest
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
        test-tls: [true, false]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache installers
        uses: actions/cache@v5
        with:
          # Note: the cache path is relative to the workspace directory
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
          path: ~/installers
          key: ${{ runner.os }}-v0-${{ hashFiles('testdata/versions.json') }}
      - name: Install and start RabbitMQ
        run: ./.ci/windows/gha-setup.ps1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install hatch "virtualenv<21.0.0"
      - name: Test with pytest
        run: hatch run test -v --cov=pika --cov-report=xml:coverage.xml ${{ matrix.test-tls && '--use-tls' || '' }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: windows-py${{ matrix.python-version }}-tls-${{ matrix.test-tls }}
          disable_search: true
          fail_ci_if_error: false
  get-versions:
    name: read pinned versions
    runs-on: ubuntu-latest
    outputs:
      rabbitmq: ${{ steps.v.outputs.rabbitmq }}
    steps:
      - uses: actions/checkout@v6
      - id: v
        run: echo "rabbitmq=$(jq -r .rabbitmq testdata/versions.json)" >> $GITHUB_OUTPUT

  build-linux:
    name: build/test on ubuntu-22.04
    runs-on: ubuntu-22.04
    needs: get-versions
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    services:
      rabbitmq:
        image: rabbitmq:${{ needs.get-versions.outputs.rabbitmq }}
        ports:
          - 5672:5672
          - 5671:5671
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install hatch "virtualenv<21.0.0"
      - name: Test with pytest
        run: hatch run test -v --cov=pika --cov-report=xml:coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          disable_search: true
          flags: linux-py${{ matrix.python-version }}
          fail_ci_if_error: false
  build-macos:
    name: build/test on macos-15-intel
    runs-on: macos-15-intel
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install and start RabbitMQ
        run: ./.ci/macos/gha-setup.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install hatch "virtualenv<21.0.0"
      - name: Test with pytest
        run: hatch run test -v --cov=pika --cov-report=xml:coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          disable_search: true
          flags: macos-py${{ matrix.python-version }}
          fail_ci_if_error: false
