name: lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  ruff:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Run ruff check
        run: |
          pip install hatch
          hatch run lint
