name: pika

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test-modern:
    uses: ./.github/workflows/_test.yaml
    with:
      python-versions: '["3.10","3.11","3.12","3.13","3.14"]'
      ubuntu-runner: ubuntu-latest
      macos-runner: macos-latest
      legacy: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-legacy:
    uses: ./.github/workflows/_test.yaml
    with:
      python-versions: '["3.7","3.8","3.9"]'
      ubuntu-runner: ubuntu-22.04
      macos-runner: macos-15-intel
      legacy: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
