name: publish

on:
  create:
    tags:
      - '*'
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yaml
  call-publish-nuget:
    uses: ./.github/workflows/publish-pypi.yaml
    needs: call-build-test
    secrets: inherit
