name: yapf

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  yapf:
    name: yapf check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install yapf
        run: pip install yapf
      - name: Run yapf
        run: yapf --diff --style google --recursive --exclude 'pika/spec.py' pika/
